[package]
name    = "ide"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enso-callback        = { version = "0.1.0" , path = "../lib/callback"             }
enso-data            = { version = "0.1.1"                                        }
enso-frp             = { version = "0.1.0" , path = "../lib/frp"                  }
enso-logger          = { version = "0.1.2"                                        }
enso-prelude         = { version = "0.1.4"                                        }
enso-shapely         = { version = "0.1.1"                                        }
ensogl               = { version = "0.1.0" , path = "../ensogl"                   }
ensogl-examples      = { version = "0.1.0" , path = "../ensogl/example"           }
ensogl-gui-list-view = { version = "0.1.0" , path = "../ensogl/lib/list-view"     }
ensogl-system-web    = { version = "0.1.0" , path = "../lib/system/web"           }
ensogl-text          = { version = "0.1.0" , path = "../ensogl/lib/text"          }
ensogl-text-msdf-sys = { version = "0.1.0" , path = "../ensogl/lib/text/msdf-sys" }
ensogl-theme         = { version = "0.1.0" , path = "../ensogl/lib/theme"         }
fuzzly               = { version = "0.1.0" , path = "../lib/fuzzly"               }

ast                      = { version = "0.1.0"  , path = "lib/ast/impl"      }
ide-view                 = { version = "0.1.0"  , path = "view" }
enso-protocol            = { version = "0.1.0"  , path = "lib/enso-protocol" }
json-rpc                 = { version = "0.1.0"  , path = "lib/json-rpc"      }
parser                   = { version = "0.1.0"  , path = "lib/parser"        }
utils                    = { version = "0.1.0"  , path = "lib/utils"         }
span-tree                = { version = "0.1.0"  , path = "lib/span-tree"     }

bimap                    = { version = "0.4.0"                                               }
console_error_panic_hook = { version = "0.1.6"                                               }
failure                  = { version = "0.1.6"                                               }
flo_stream               = { version = "0.4.0"                                               }
futures                  = { version = "0.3.1"                                               }
itertools                = { version = "0.8.1"                                               }
js-sys                   = { version = "0.3.35"                                              }
mockall                  = { version = "0.7.1"  , features = ["nightly"]                     }
nalgebra                 = { version = "0.21.1" , features = ["serde-serialize"]             }
serde                    = { version = "1.0"    , features = ["derive"]                      }
serde_json               = { version = "1.0"                                                 }
uuid                     = { version = "0.8"    , features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen             = { version = "=0.2.58"                                             }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
websocket = "0.23.0"

[dev-dependencies]
regex             = { version = "1.3.6" }
wasm-bindgen-test = { version = "0.3.8" }

[dependencies.web-sys]
version = "0.3.22"
features = [
  'BinaryType',
  'Blob',
  'console',
  'CloseEvent',
  'Document',
  'Element',
  "ErrorEvent",
  "MessageEvent",
  'HtmlElement',
  'Node',
  'WebSocket',
  'Window',
]
