[package]
name    = "ide"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ensogl                   = { version = "0.1.0"  , path = "../ensogl"            }
ensogl-core-msdf-sys     = { version = "0.1.0"  , path = "../ensogl/msdf-sys"   }
ensogl-system-web        = { version = "0.1.0"  , path = "../lib/system/web"    }
data                     = { version = "0.1.0"  , path = "../lib/data"          }
enso-frp                 = { version = "0.1.0"  , path = "../lib/frp"           }
enso-prelude             = { version = "0.1.0"  , path = "../lib/prelude"       }
graph-editor             = { version = "0.1.0"  , path = "../lib/graph-editor"  }
shapely                  = { version = "0.1.0"  , path = "../lib/shapely/impl"  }

ast                      = { version = "0.1.0"  , path = "ast/impl"             }
file-manager-client      = { version = "0.1.0"  , path = "file-manager"         }
json-rpc                 = { version = "0.1.0"  , path = "json-rpc"             }
parser                   = { version = "0.1.0"  , path = "parser"               }
utils                    = { version = "0.1.0"  , path = "utils"                }

console_error_panic_hook = { version = "0.1.6"                                   }
failure                  = { version = "0.1.6"                                   }
flo_stream               = { version = "0.4.0"                                   }
futures                  = { version = "0.3.1"                                   }
nalgebra                 = { version = "0.19.0" , features = ["serde-serialize"] }
js-sys                   = { version = "0.3.35"                                  }
serde                    = { version = "1.0"    , features = ["derive"]          }
serde_json               = { version = "1.0"                                     }
uuid                     = { version = "0.8"    , features = ["serde", "v5"]     }
wasm-bindgen             = { version = "=0.2.58"                                 }
wasm-bindgen-test        = { version = "0.3.8"                                   }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
websocket = "0.23.0"

[dependencies.web-sys]
version = "0.3.22"
features = [
  'Blob',
  'console',
  'CloseEvent',
  'Document',
  'Element',
  "ErrorEvent",
  "MessageEvent",
  'HtmlElement',
  'Node',
  'WebSocket',
  'Window',
]
