[package]
name = "logstat"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
lazy_static = "1.4.0"
enso-prelude = { path = "../../../lib/rust/prelude" }
regex = { workspace = true }
time = { version = "0.3", features = ["formatting", "parsing"] }
tokio = { workspace = true }
tokio-stream = { version = "0.1.9", features = ["io-util"] }
