[package]
name = "macro-utils"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[dependencies]
prelude        = { version = "0.1.0"  , path = "../prelude" }
proc-macro2    = "1.0"
quote          = "1.0"

[dependencies.syn]
version = "1.0"
features = [
  'extra-traits',
  'full' # for syn::ItemStruct
]
