[package]
name = "engine-model"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
