[package]
name = "enso-debug-scene"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
debug-scene-interface = { path = "interface" }
debug-scene-visualization = { path = "visualization" }
