[workspace]
members = [
  "build",
  "ensogl",
  "ensogl/example",
  "ensogl/lib/core",
  "ensogl/lib/components",
  "ensogl/lib/theme",
  "ensogl/lib/text/embedded-fonts",
  "ensogl/lib/text/msdf-sys",
  "ensogl/lib/text",
  "ensogl/lib/web",
  "ide",
  "ide/controller",
  "ide/controller/double-representation",
  "ide/controller/engine-model",
  "ide/controller/engine-protocol",
  "ide/lib/args",
  "ide/lib/ast/impl",
  "ide/lib/ast/macros",
  "ide/lib/json-rpc",
  "ide/lib/parser",
  "ide/lib/span-tree",
  "ide/lib/span-tree/example",
  "ide/lib/utils",
  "ide/view",
  "ide/view/graph-editor",
  "lib/callback",
  "lib/code-builder",
  "lib/config",
  "lib/eval-tt",
  "lib/frp",
  "lib/fuzzly",
  "lib/shortcuts",
  "lib/shortcuts/example",
  "lib/system/web",
  "lib/types",
]

[profile.dev]
opt-level = 0
lto = false
debug = true

[profile.release]
opt-level = 3
lto = true
debug = false

[profile.bench]
opt-level = 3
lto = true
debug = false

[profile.test]
opt-level = 0
lto = false
debug = true

## These patch versions exist to allow local development of these libraries alongside the IDE. It
## assumes you have `rust-lib` in the same directory as `ide`. See:
## https://github.com/enso-org/rust-lib/blob/main/docs/CONTRIBUTING.md#developing-in-conjunction-with-enso--ide
#[patch.crates-io]
#enso-automata = { path = '../../../rust-lib/src/automata' }
#enso-data = { path = '../../../rust-lib/src/data' }
#enso-generics = { path = '../../../rust-lib/src/generics' }
#enso-logger = { path = '../../../rust-lib/src/logger' }
#enso-macro-utils = { path = '../../../rust-lib/src/macro-utils' }
#enso-optics = { path = '../../../rust-lib/src/optics' }
#enso-prelude = { path = '../../../rust-lib/src/prelude' }
#enso-shapely = { path = '../../../rust-lib/src/shapely/impl' }
#enso-shapely-macros = { path = '../../../rust-lib/src/shapely/macros' }
