[package]
name = "enso-suggestion-database"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enso-prelude = { path = "../../../lib/rust/prelude" }
enso-doc-parser = { path = "../../../lib/rust/parser/doc-parser" }
convert_case = { workspace = true }
span-tree = { path = "../language/span-tree" }
ast = { path = "../language/ast/impl" }
parser = { path = "../language/parser" }
enso-profiler = { path = "../../../lib/rust/profiler" }
enso-text = { path = "../../../lib/rust/text" }
double-representation = { path = "../controller/double-representation" }
engine-protocol = { path = "../controller/engine-protocol" }
enso-data-structures = { path = "../../../lib/rust/data-structures" }
ensogl-icons = { path = "../../../lib/rust/ensogl/component/icons" }
flo_stream = { version = "0.4.0" }
failure = { workspace = true }
enso-notification = { path = "../../../lib/rust/notification" }

[dev-dependencies]
futures = { workspace = true }
enso-executor = { path = "../../../lib/rust/executor" }
wasm-bindgen-test = { workspace = true }
