[package]
name = "wstest"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[dependencies]
base64 = "0.13.0"
clap = { version = "3", features = ["derive"] }
either = "1.7.0"
futures = "0.3"
enso-prelude = { path = "../../../lib/rust/prelude" }
regex = "1.6.0"
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1.19.2", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["io-util"] }
url = "2.2"
websocket-lite = "0.5"
