[package]
name = "enso-span-tree-example"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast = { path = "../../ast/impl" }
enso-text = { path = "../../../../../lib/rust/text" }
span-tree = { path = "../../span-tree" }
enso-web = { path = "../../../../../lib/rust/web" }
enso-prelude = { path = "../../../../../lib/rust/prelude"}
enso-logger = { path = "../../../../../lib/rust/logger"}
wasm-bindgen = { version = "=0.2.58", features = [
  "nightly",
  "serde-serialize"
] }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }

[dependencies.web-sys]
version = "0.3.4"
features = []
