[package]
name = "welcome-screen"
version = "0.1.0"
edition = "2021"
authors = ["Enso Team <contact@enso.org>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ensogl = { path = "../../../../lib/rust/ensogl" }
enso-frp = { path = "../../../../lib/rust/frp" }
wasm-bindgen = { version = "=0.2.58", features = [
  "nightly",
  "serde-serialize"
] }
web-sys = { version = "0.3.4", features = [] }
