[package]
name = "engine-protocol"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
enso-data-structures = { path = "../../../../lib/rust/data-structures" }
enso-prelude = { path = "../../../../lib/rust/prelude" }
enso-shapely = { path = "../../../../lib/rust/shapely" }
enso-text = { path = "../../../../lib/rust/text" }
failure = { workspace = true }
flatbuffers = { version = "0.5" }
futures = { workspace = true }
hex = { version = "0.4.2" }
json-rpc = { path = "../../../../lib/rust/json-rpc" }
mockall = { version = "0.7.1", features = ["nightly"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
sha3 = { version = "0.8.2" }
strum = "0.24.0"
strum_macros = "0.24.0"
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
enso-web = { path = "../../../../lib/rust/web" }

[build-dependencies]
enso-build-utilities = { path = "../../../../build/deprecated/build-utils" }
bytes = { workspace = true }
flatc-rust = { version = "0.1.2" }
futures = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
# Zip is needed because the build script downloads and extracts artifacts from the Engine.
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
