[package]
name = "double-representation"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast = { version = "0.1.0", path = "../../lib/ast/impl" }
engine-protocol = { version = "0.1.0", path = "../engine-protocol" }
parser = { version = "0.1.0", path = "../../lib/parser" }
utils = { version = "0.1.0", path = "../../lib/utils" }
enso-data = { path = "../../../../../../lib/rust/data"}
enso-logger = { path = "../../../../../../lib/rust/logger"}
enso-prelude = { path = "../../../../../../lib/rust/prelude"}
failure = { version = "0.1.6" }
itertools = { version = "0.10.0" }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }

[dev-dependencies]
regex = { version = "1.3.6" }
wasm-bindgen-test = { version = "0.3.8" }
