version: 2
jobs:
  luna-compiler:
    environment:
      GHC_RTS: -M3G
    docker:
      - image: lunalang/luna-ci
    steps:
      - checkout
      - restore-cache:
          key: stack-v1-{{ checksum "config/snapshot.yaml" }}
      - run: stack setup
      - run: stack build --interleaved-output --ghc-options="-pgmc gcc-8" --test --copy-bins
      - save-cache:
          key: stack-v1-{{ checksum "config/snapshot.yaml" }}
          when: always
          paths:
              - "~/.stack"
              - ".stack-work"
      - run:
          command: LD_PRELOAD=/root/.stack/programs/x86_64-linux/ghc-8.4.4/lib/ghc-8.4.4/rts/libffi.so.7 /root/project/dist/bin/public/luna run --target=/root/project/stdlib/StdTest
          no_output_timeout: 45m


workflows:
  version: 2
  percommit:
    jobs:
      - luna-compiler
