# https://aka.ms/yaml

trigger:
  branches:
    include: [ "*" ]
  paths:
    exclude:
      - doc/*

jobs:
- job: Ubuntu
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu-16.04'
  container:
    image: lunalang/luna-ci
  steps:
  - script: stack build --only-snapshot
    displayName: Setup GHC & Snapshot Deps
  - script: stack build --ghc-options="-pgmc gcc-8" --test --copy-bins
    displayName: Build Luna
  - script: LD_PRELOAD=~/.stack/programs/x86_64-linux/ghc-8.4.4/lib/ghc-8.4.4/rts/libffi.so.7 stack run -- run --target=$(Build.SourcesDirectory)/stdlib/StdTest
    displayName: Run Tests
  - script: stack build_package.hs --check-script
    displayName: Check Package Script

- job: macOS
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: >
      curl -sSL https://get.haskellstack.org/ | sh
    displayName: Install Stack
  - script: >
      brew update
      && brew install pkg-config libffi zmq
    displayName: Install Brew Libraries
  - script: >
      eval $(brew shellenv)
      && export LDFLAGS="-L/usr/local/opt/libffi/lib"
      && export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
      && stack build
    displayName: Build Luna
  - script: stack run -- run --target=$(Build.SourcesDirectory)/stdlib/StdTest
    displayName: Run Tests
  - script: stack build_package.hs --check-script
    displayName: Check Package Script

- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: |
      curl -sS -o stack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
      7z x stack.zip -y -oC:\stack stack.exe
    displayName: Install Stack
  - script: C:\stack\stack exec -- pacman --noconfirm -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-libffi
    displayName:  Install MSYS2 Dependencies
  - script: C:\stack\stack build
    displayName: Build Luna
  - script: C:\stack\stack run -- run --target=$(Build.SourcesDirectory)/stdlib/StdTest
    displayName: Run Tests
  - script: C:\stack\stack build_package.hs --check-script
    displayName: Check Package Script
