[package]
name    = "shapely-macros"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
proc-macro = true

[features]
default = []

[dependencies]
Inflector      = "0.11.4"
proc-macro2    = "1.0"
quote          = "1.0"

macro-utils    = { version = "0.1.0"  , path = "../../macro-utils" }
prelude        = { version = "0.1.0"  , path = "../../prelude" }

[dependencies.syn]
version = "1.0"
features = [
  'extra-traits',
  'full' # for syn::File and syn::ItemFn
]
