[package]
name    = "ast"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more              = { version = "0.15.0"                           }
failure                  = { version = "0.1.5"                            }
serde                    = { version = "1.0", features = ["derive", "rc"] }
serde_json               = { version = "1.0"                              }
shrinkwraprs             = { version = "0.2.1"                            }

ast-macros               = { version = "0.1.0", path = "../macros"          }
prelude                  = { version = "0.1.0", path = "../../prelude"      }
shapely                  = { version = "0.1.0", path = "../../shapely/core" }
