[package]
name = "ide-view"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast = { path = "../lib/ast/impl" }
enso-args = { path = "../lib/args" }
enso-frp = { path = "../../lib/frp" }
enso-logger = { path = "../../../../../lib/rust/logger"}
enso-prelude = { path = "../../../../../lib/rust/prelude"}
enso-shapely = { path = "../../../../../lib/rust/shapely/impl"}
engine-protocol = { path = "../controller/engine-protocol" }
ensogl = { path = "../../ensogl" }
enso-config = { path = "../../lib/config" }
ensogl-gui-components = { path = "../../ensogl/lib/components" }
ensogl-text = { path = "../../ensogl/lib/text" }
ensogl-text-msdf-sys = { path = "../../ensogl/lib/text/msdf-sys" }
ensogl-theme = { path = "../../ensogl/lib/theme" }
ide-view-graph-editor = { path = "graph-editor" }
parser = { path = "../lib/parser" }
span-tree = { path = "../lib/span-tree" }
js-sys = { version = "0.3.28" }
nalgebra = { version = "0.26.1", features = ["serde-serialize"] }
ordered-float = { version = "2.7.0" }
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = { version = "=0.2.58", features = [
  "nightly",
  "serde-serialize"
] }

[dependencies.web-sys]
version = "0.3.4"
features = []
