[package]
name = "ide-view-graph-editor"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
analytics = { path = "../../analytics" }
ast = { path = "../../language/ast/impl" }
base64 = "0.13"
bimap = { version = "0.4.0" }
derivative = "2.2.0"
engine-protocol = { path = "../../controller/engine-protocol" }
enso-config = { path = "../../config" }
enso-frp = { path = "../../../../lib/rust/frp" }
enso-prelude = { path = "../../../../lib/rust/prelude" }
enso-shapely = { path = "../../../../lib/rust/shapely" }
enso-text = { path = "../../../../lib/rust/text" }
ensogl = { path = "../../../../lib/rust/ensogl" }
ensogl-component = { path = "../../../../lib/rust/ensogl/component" }
ensogl-derive-theme = { path = "../../../../lib/rust/ensogl/app/theme/derive" }
ensogl-drop-manager = { path = "../../../../lib/rust/ensogl/component/drop-manager" }
ensogl-hardcoded-theme = { path = "../../../../lib/rust/ensogl/app/theme/hardcoded" }
ensogl-text-msdf = { path = "../../../../lib/rust/ensogl/component/text/src/font/msdf" }
failure = { workspace = true }
ide-view-execution-environment-selector = { path = "../execution-environment-selector" }
ide-view-component-list-panel-icons = { path = "../component-browser/component-list-panel/icons" }
indexmap = "1.9.2"
js-sys = { workspace = true }
nalgebra = { workspace = true }
ordered-float = { workspace = true }
parser = { path = "../../language/parser" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = { workspace = true }
serde_json = { workspace = true }
sourcemap = "6.0"
span-tree = { path = "../../language/span-tree" }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = { workspace = true }
bitflags = { workspace = true }

[dependencies.web-sys]
version = "0.3.4"
features = ["TextMetrics", 'CanvasRenderingContext2d', 'HtmlHeadElement']

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
