[package]
name = "debug-scene-component-list-panel-view"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enso-frp = { path = "../../../../../lib/rust/frp" }
enso-profiler = { path = "../../../../../lib/rust/profiler" }
ensogl-core = { path = "../../../../../lib/rust/ensogl/core" }
ensogl-hardcoded-theme = { path = "../../../../../lib/rust/ensogl/app/theme/hardcoded" }
ensogl-grid-view = { path = "../../../../../lib/rust/ensogl/component/grid-view" }
ensogl-selector = { path = "../../../../../lib/rust/ensogl/component/selector" }
ensogl-text = { path = "../../../../../lib/rust/ensogl/component/text" }
ensogl-icons = { path = "../../../../../lib/rust/ensogl/component/icons" }
ensogl-text-msdf = { path = "../../../../../lib/rust/ensogl/component/text/src/font/msdf" }
ide-view-component-list-panel = { path = "../../component-browser/component-list-panel" }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }

# Stop wasm-pack from running wasm-opt, because we run it from our build scripts in order to customize options.
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
