[package]
name = "ide-view-graph-editor"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
analytics = { version = "0.1.0", path = "../../lib/analytics" }
ast = { version = "0.1.0", path = "../../lib/ast/impl" }
bimap = { version = "0.4.0"}
enso-args = { version = "0.1.0", path = "../../lib/args" }
enso-frp = { version = "0.1.0", path = "../../../lib/frp" }
enso-logger = { path = "../../../../../../lib/rust/logger"}
enso-prelude = { path = "../../../../../../lib/rust/prelude"}
enso-protocol = { version = "0.1.0", path = "../../lib/enso-protocol" }
enso-shapely = { path = "../../../../../../lib/rust/shapely/impl"}
ensogl = { version = "0.1.0", path = "../../../ensogl" }
ensogl-gui-components = { version = "0.1.0", path = "../../../ensogl/lib/components" }
ensogl-text = { version = "0.1.0", path = "../../../ensogl/lib/text" }
ensogl-text-msdf-sys = { version = "0.1.0", path = "../../../ensogl/lib/text/msdf-sys" }
ensogl-theme = { version = "0.1.0", path = "../../../ensogl/lib/theme" }
ensogl-web = { version = "0.1.0", path = "../../../ensogl/lib/web" }
failure = { version = "0.1.8" }
ordered-float = {version = "1.0"}
span-tree = { version = "0.1.0", path = "../../lib/span-tree" }
js-sys = { version = "0.3.28" }
nalgebra = { version = "0.26.1", features = ["serde-serialize"] }
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = { version = "=0.2.58", features = ["nightly", "serde-serialize"] }

[dependencies.web-sys]
version = "0.3.4"
features = []
