[package]
name = "parser-scala"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast = { path = "../ast/impl" }
enso-prelude = { path = "../../../../lib/rust/prelude" }
enso-profiler = { path = "../../../../lib/rust/profiler" }
console_error_panic_hook = { workspace = true }
failure = { workspace = true }
js-sys = { workspace = true }
matches = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["unbounded_depth"] }
wasm-bindgen = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[build-dependencies]
ide-ci = { path = "../../../../build/ci_utils" }
bytes = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
websocket = "0.26.5"
