[package]
name = "ide-view-component-list-panel-icons"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[dependencies]
ensogl-core = { path = "../../../../../../lib/rust/ensogl/core" }
failure = "0.1.8"
