[package]
name = "file-manager-client"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures    = "0.3.1"
paste      = "0.1.6"
serde_json = "1.0"

chrono     = { version = "0.4"    , features = ["serde"] }
serde      = { version = "1.0"    , features = ["derive"] }
uuid       = { version = "0.8"    , features = ["serde", "v5"] }

json-rpc   = { version = "0.1.0"  , path = "../json-rpc" }
prelude    = { version = "0.1.0"  , path = "../prelude" }
utils      = { version = "0.1.0"  , path = "../utils" }
