[package]
name = "enso-debug-scene"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
debug-scene-component-list-panel-view = { path = "component-list-panel-view" }
debug-scene-documentation = { path = "documentation" }
debug-scene-graph-editor-edges = { path = "graph-editor-edges" }
debug-scene-icons = { path = "icons" }
debug-scene-interface = { path = "interface" }
debug-scene-text-grid-visualization = { path = "text-grid-visualization" }
debug-scene-visualization = { path = "visualization" }
debug-scene-execution-environment-dropdown = { path = "execution-environment-dropdown" }

# Stop wasm-pack from running wasm-opt, because we run it from our build scripts in order to customize options.
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
