[package]
name    = "enso-protocol"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
json-rpc     = { version = "0.1.0"  , path = "../json-rpc" }
enso-prelude = { version = "0.1.0"  , path = "../../lib/prelude" }
shapely      = { version = "0.1.0"  , path = "../../lib/shapely/impl" }
utils        = { version = "0.1.0"  , path = "../utils" }

chrono     = { version = "0.4"    , features = ["serde"] }
futures    = { version = "0.3.1" }
serde      = { version = "1.0"    , features = ["derive"] }
serde_json = { version = "1.0"   }
uuid       = { version = "0.8"    , features = ["serde", "v5"] }
