[workspace]

members = [
    "build",
    "ensogl",
    "ensogl/example",
    "ensogl/lib/core",
    "ensogl/lib/list-view",
    "ensogl/lib/theme",
    "ensogl/lib/text/embedded-fonts",
    "ensogl/lib/text/msdf-sys",
    "ensogl/lib/text",
    "ide",
    "ide/lib/ast/impl",
    "ide/lib/ast/macros",
    "ide/lib/enso-protocol",
    "ide/lib/json-rpc",
    "ide/lib/parser",
    "ide/lib/span-tree",
    "ide/lib/utils",
    "ide/view",
    "ide/view/graph-editor",

    "lib/automata",
    "lib/callback",
    "lib/code-builder",
    "lib/data",
    "lib/enso-macro-utils",
    "lib/enso-prelude",
    "lib/enso-shapely/impl",
    "lib/enso-shapely/macros",
    "lib/eval-tt",
    "lib/frp",
    "lib/fuzzly",
    "lib/generics",
    "lib/logger",
    "lib/optics",
    "lib/shortcuts",
    "lib/shortcuts/example",
    "lib/system/web",
    "lib/types",
]

[profile.dev]
opt-level = 0
lto       = false
debug     = true

[profile.release]
opt-level = 3
lto       = true
debug     = false

[profile.bench]
opt-level = 3
lto       = true
debug     = false

[profile.test]
opt-level = 0
lto       = false
debug     = true
