unstable_features = true
required_version  = "1.4.8"

# Basic Configuration
edition                     = "2018"
newline_style               = "Unix"
format_code_in_doc_comments = true
format_macro_matchers       = true
use_field_init_shorthand    = true
use_small_heuristics        = "Max"
use_try_shorthand           = true
where_single_line           = true
condense_wildcard_suffixes  = true # `let (a,b,_,_) = x` -> `let (a,b,..) = x`

# Max Width
max_width              = 80
error_on_line_overflow = true
error_on_unformatted   = true
format_strings         = true
wrap_comments          = true

# Comments
normalize_comments       = true
normalize_doc_attributes = true

# Imports
#merge_imports = true


# Newlines
overflow_delimited_expr = true

# Ordering
reorder_impl_items = true

# Vertical Alignment
struct_field_align_threshold = 80
enum_discrim_align_threshold = 80
spaces_around_ranges         = true
brace_style                  = "PreferSameLine"

# Reporting
report_fixme = "Unnumbered"
report_todo  = "Unnumbered"
