[package]
name = "span-tree"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[dependencies]
ast = { path = "../ast/impl" }
enso-data-structures = { path = "../../../../lib/rust/data-structures" }
enso-text = { path = "../../../../lib/rust/text" }
enso-prelude = { path = "../../../../lib/rust/prelude" }
enso-profiler = { path = "../../../../lib/rust/profiler" }
failure = { workspace = true }

[dev-dependencies]
parser = { path = "../parser" }
wasm-bindgen-test = { workspace = true }
