# The name of an object created in the global window scope. This object will contain functions
# to control the IDE, like the `main` function, and also the configuration object.
windowAppScopeName: "enso"

# The configuration object nested inside of the `windowAppScopeName` object containing all
# startup configuration options. See usages of this variable to learn more about available
# options.
windowAppScopeConfigName: "config"

# The configuration object nested inside of the `windowAppScopeName` object containing theming
# utilities and allowing for runtime theme modification.
windowAppScopeThemeName: "theme"

# The URL to the JSON-RPC endpoint to the Project Manager.
# This MUST be kept in sync with the corresponding value in `app/gui/src/constants.rs`.
projectManagerEndpoint: "ws://127.0.0.1:30535"

# TODO [ao] add description here.
minimumSupportedVersion": "2.0.0-alpha.6"

# The minimum engine version supported by the application. The projects opened with the older versions
# will have the "Unsupported engine version" message displayed.
engineVersionSupported: "2023.1.1"

# The minimum language edition supported by the application. It will be displayed as edition user
# should put in their package.yaml file to have project compatible with the IDE.
languageEditionSupported: "2023.1.1"
