[package]
name = "ide-view-graph-editor"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast = { version = "0.1.0", path = "../../lib/ast/impl" }
enso-frp = { version = "0.1.0", path = "../../../lib/frp" }
enso-logger = { version = "0.2.1" }
enso-prelude = { version = "0.1.8" }
enso-protocol = { version = "0.1.0", path = "../../lib/enso-protocol" }
enso-shapely = { version = "0.1.2" }
ensogl = { version = "0.1.0", path = "../../../ensogl" }
ensogl-gui-components = { version = "0.1.0", path = "../../../ensogl/lib/components" }
ensogl-text = { version = "0.1.0", path = "../../../ensogl/lib/text" }
ensogl-text-msdf-sys = { version = "0.1.0", path = "../../../ensogl/lib/text/msdf-sys" }
ensogl-theme = { version = "0.1.0", path = "../../../ensogl/lib/theme" }
span-tree = { version = "0.1.0", path = "../../lib/span-tree" }
js-sys = { version = "0.3.28" }
nalgebra = { version = "0.21.1", features = ["serde-serialize"] }
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = { version = "=0.2.58", features = ["nightly", "serde-serialize"] }

[dependencies.web-sys]
version = "0.3.4"
features = []
