---
name: GUI CI
"on":
  push: {}
jobs:
  ide-ci-actions-workflow-definition-job-build-project-manager-linux:
    name: Build Project Manager (linux)
    runs-on:
      - self-hosted
      - Linux
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh project-manager"
        shell: bash
  ide-ci-actions-workflow-definition-job-native-test-linux:
    name: Native GUI tests (linux)
    runs-on:
      - self-hosted
      - Linux
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh wasm test --no-wasm"
        shell: bash
  ide-ci-actions-workflow-definition-job-wasm-test-linux:
    name: WASM GUI tests (linux)
    runs-on:
      - self-hosted
      - Linux
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh wasm test --no-native"
        shell: bash
  ide-ci-actions-workflow-definition-job-build-project-manager-windows:
    name: Build Project Manager (windows)
    runs-on:
      - self-hosted
      - Windows
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: ".\\run.cmd --help"
        shell: cmd
      - run: ".\\run.cmd project-manager"
        shell: cmd
  ide-ci-actions-workflow-definition-job-build-project-manager-macos:
    name: Build Project Manager (macos)
    runs-on:
      - macos-latest
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh project-manager"
        shell: bash
  ide-ci-actions-workflow-definition-job-package-ide-macos:
    name: Package IDE (macos)
    needs:
      - ide-ci-actions-workflow-definition-job-build-wasm-macos
      - ide-ci-actions-workflow-definition-job-build-project-manager-macos
    runs-on:
      - macos-latest
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh ide build --wasm-source current-ci-run --project-manager-source current-ci-run"
        shell: bash
  ide-ci-actions-workflow-definition-job-build-wasm-macos:
    name: Build GUI (WASM) (macos)
    runs-on:
      - macos-latest
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh wasm build"
        shell: bash
  ide-ci-actions-workflow-definition-job-package-ide-linux:
    name: Package IDE (linux)
    needs:
      - ide-ci-actions-workflow-definition-job-build-wasm-linux
      - ide-ci-actions-workflow-definition-job-build-project-manager-linux
    runs-on:
      - self-hosted
      - Linux
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh ide build --wasm-source current-ci-run --project-manager-source current-ci-run"
        shell: bash
  ide-ci-actions-workflow-definition-job-integration-test-linux:
    name: IDE integration tests (linux)
    needs:
      - ide-ci-actions-workflow-definition-job-build-project-manager-linux
    runs-on:
      - self-hosted
      - Linux
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh ide integration-test --project-manager-source current-ci-run"
        shell: bash
  ide-ci-actions-workflow-definition-job-build-wasm-windows:
    name: Build GUI (WASM) (windows)
    runs-on:
      - self-hosted
      - Windows
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: ".\\run.cmd --help"
        shell: cmd
      - run: ".\\run.cmd wasm build"
        shell: cmd
  ide-ci-actions-workflow-definition-job-package-ide-windows:
    name: Package IDE (windows)
    needs:
      - ide-ci-actions-workflow-definition-job-build-wasm-windows
      - ide-ci-actions-workflow-definition-job-build-project-manager-windows
    runs-on:
      - self-hosted
      - Windows
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: ".\\run.cmd --help"
        shell: cmd
      - run: ".\\run.cmd ide build --wasm-source current-ci-run --project-manager-source current-ci-run"
        shell: cmd
  ide-ci-actions-workflow-definition-job-lint-linux:
    name: Lint (linux)
    runs-on:
      - self-hosted
      - Linux
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh lint"
        shell: bash
  ide-ci-actions-workflow-definition-job-build-wasm-linux:
    name: Build GUI (WASM) (linux)
    runs-on:
      - self-hosted
      - Linux
      - engine
    steps:
      - name: Setup conda (GH runners only)
        uses: s-weigand/setup-conda@v1.0.5
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          update-conda: false
          conda-channels: "anaconda, conda-forge"
      - name: Installing wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        if: "startsWith(runner.name, 'GitHub Actions') || startsWith(runner.name, 'Hosted Agent')"
        with:
          version: latest
      - name: Setup the Artifact API environment
        uses: actions/github-script@v6
        with:
          script: "core.exportVariable(\"ACTIONS_RUNTIME_TOKEN\", process.env[\"ACTIONS_RUNTIME_TOKEN\"])\ncore.exportVariable(\"ACTIONS_RUNTIME_URL\", process.env[\"ACTIONS_RUNTIME_URL\"])\ncore.exportVariable(\"GITHUB_RETENTION_DAYS\", process.env[\"GITHUB_RETENTION_DAYS\"])"
      - name: Checking out the repository
        uses: actions/checkout@v3
        with:
          clean: false
      - run: "./run.sh --help"
        shell: bash
      - run: "./run.sh wasm build"
        shell: bash
